version: "3"

services:
  app-ci-test:
    container_name: "node16-with-verdaccio"
    ports:
      - '4873:4873'
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4873 || exit 1
      interval: 3s
      timeout: 1s
      retries: 5
