import { MAX_PIECE_SIZE, MIN_PIECE_SIZE } from '@cere-ddc-sdk/ddc';

export { MAX_PIECE_SIZE as MAX_BUFFER_SIZE, MIN_PIECE_SIZE as MIN_BUFFER_SIZE };

export const DEFAULT_BUFFER_SIZE = MAX_PIECE_SIZE;
