name: 'CI'
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - edited
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
          registry-url: 'https://registry.npmjs.org'
      - name: NPM set NPM_TOKEN
        run: npm set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_TOKEN }} --location project
      - name: check
        run: cat .npmrc && npm whoami
      - name: Install packages
        run: yarn
      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler
      - name: Check protoc version
        run: protoc --version
      - name: Compile proto
        run: npm run compile
      - name: Integration tests
        run: npm test
      - name: NPM set register
        run: npm set registry http://localhost:4873/
      - name: Increase version
        run: node scripts/release.js --major
      - name: Publishing dry-run
        run: node scripts/ci-test.mjs
