name: 'CI'
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - edited
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Clean cache NPM
        run: npm cache clean --force
      - name: Install packages
        run: npm install
      - name: Compile
        run: npm run compile
      - name: Publish package
        run: npm publish --workspaces --access public