name: 'CI'
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - edited
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
          registry-url: 'https://registry.npmjs.org'
      - name: Install packages
        run: npm install
      - name: Compile
        run: npm run compile
      - name: Unpublish package content-addressable-storage
        run: npm unpublish @cere-ddc-sdk/content-addressable-storage@1.2.0
      - name: Unpublish package core
        run: npm unpublish @cere-ddc-sdk/core@1.2.0
      - name: Unpublish package ddc-client
        run: npm unpublish @cere-ddc-sdk/ddc-client@1.2.0
      - name: Unpublish package file-storage
        run: npm unpublish @cere-ddc-sdk/file-storage@1.2.0
      - name: Unpublish package key-value-storage
        run: npm unpublish @cere-ddc-sdk/key-value-storage@1.2.0
      - name: Unpublish package proto
        run: npm unpublish @cere-ddc-sdk/proto@1.2.0
      - name: Unpublish package smart-contract
        run: npm unpublish @cere-ddc-sdk/smart-contract@1.2.0