name: 'CI'
on:
  push:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: actions/setup-node@v2
        with:
          node-version: '16.20.1'
          registry-url: 'https://registry.npmjs.org'
      - name: Install packages
        run: npm install
      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler
      - name: Check protoc version
        run: protoc --version
      - name: Compile proto
        run: npm run compile
      - name: Integration tests
        run: npm test
      - name: Increase version
        run: node scripts/release.js --major
      - name: NPM set register
        run: npm set registry http://localhost:4873/
      - name: Publishing dry-run
        run: node scripts/ci-test.mjs
