name: Deploy playground

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Get Node.js version
        id: nvm
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Install packages
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Upload playground
        uses: actions/upload-pages-artifact@v1
        with:
          path: './playground/dist'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
