name: Continuous deployment
on:
  push:
    branches:
      - publish

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: Install
        run: npm install
      - name: Compile
        run: npm run compile  -ws
      - name: Publish
        run: npm publish --workspaces --access public
