name: Continuous deployment
on:
  push:
    branches:
      - publish

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run compile
      - run: npm publish --workspaces --access public
