name: 'CD release'
on:
  release:
    types: [prereleased, released]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
          registry-url: 'https://registry.npmjs.org'
          submodules: "true"
      - name: Install packages
        run: npm install
      - name: NPM set register
        run: npm set registry https://registry.npmjs.org
      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler
      - name: Check protoc version
        run: protoc --version
      - name: Compile proto
        run: npm run compile
      - name: NPM whoami
        run: npm whoami
      - name: Run tests
        run: npm run test
      - name: Publish
        run: node scripts/publish.js
  e2e-tests:
    needs: continuous-deployment
    strategy:
      matrix:
        repo: ['Cerebellum-Network/ddc-e2e-tests']
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cerebellum-Network/ddc-e2e-tests repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TRIGGER_GITHUB_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: sdk_release